version: "3"
services:
 fetchit-backend:
    # Builds the local image
    image: fetchit-backend
    build:
      context: ./backend/
      dockerfile: dev.dockerfile
    # Creates the container name
    container_name: fetchit-backend
    # Restarts unless stopped
    restart: unless-stopped
    env_file:
    - dev.env # configures the s3 system
    volumes:
      - ./backend:/home/backend/app
    # Assigns the port
    ports:
      - 5000:5000

 fetchit-frontend:
    # Builds the local image
    image: fetchit-frontend
    build:
      context: ./frontend/
      dockerfile: dev.dockerfile
    # Creates the container name
    container_name: fetchit-frontend
    # Restarts unless stopped
    restart: unless-stopped
    # Maps the directory we'll refresh if changes are detected
    # Assigns the port
    ports:
      - 3000:3000
    depends_on:
      - fetchit-backend