# Deploys a payload to the server to get the latest data
name: Deploy to Docker

on:
  push:
    branches: [ master ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Dockerize
        run: |
          cd backend/
          docker build --tag fetchit .
      - name: docker push
        env:
          REPO: ${{ secrets.REPO }}
        run: |
          docker tag fetchit $REPO
          docker push $REPO
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: ./deploy.sh && exit

